USE elderly_care_20250921;

-- 为 app_user 补齐代码实体所需、但建表 SQL 缺失的列
-- 每列均带 IF NOT EXISTS 防护，可重复执行
SET @db='elderly_care_20250921';
SET @tbl='app_user';

SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN real_name VARCHAR(100) COMMENT ''real name''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='real_name'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN gender TINYINT COMMENT ''gender:0 female 1 male''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='gender'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN birth_date DATE COMMENT ''birth date''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='birth_date'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN id_card VARCHAR(18) COMMENT ''id card no''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='id_card'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN nation VARCHAR(50) COMMENT ''nation''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='nation'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN native_place VARCHAR(100) COMMENT ''native place''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='native_place'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN marriage VARCHAR(20) COMMENT ''marriage status''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='marriage'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN education VARCHAR(50) COMMENT ''education''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='education'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN occupation VARCHAR(100) COMMENT ''occupation''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='occupation'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN work_unit VARCHAR(100) COMMENT ''work unit''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='work_unit'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN height DECIMAL(10,2) COMMENT ''height cm''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='height'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN weight DECIMAL(10,2) COMMENT ''weight kg''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='weight'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN address VARCHAR(255) COMMENT ''address''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='address'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN emergency_contact VARCHAR(50) COMMENT ''emergency contact''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='emergency_contact'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN emergency_phone VARCHAR(20) COMMENT ''emergency phone''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='emergency_phone'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;
SET @s=(SELECT IF(COUNT(*)=0,'ALTER TABLE app_user ADD COLUMN bio VARCHAR(500) COMMENT ''bio''','SELECT 1') FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME=@tbl AND COLUMN_NAME='bio'); PREPARE s FROM @s; EXECUTE s; DEALLOCATE PREPARE s;

SELECT 'DONE' AS result;
